stages:
  - build
#  - deploy

build:
  image: maven:3.6.0-jdk-11
  stage: build
  script:
    - export NEXUS_SERVER="10.113.80.244"
    - echo "@skills:registry=http://${NEXUS_SERVER}/repository/skills-registry/" > ~/.npmrc
    - cat ~/.npmrc
    - mkdir ~/.m2
    - echo "<settings><mirrors><mirror><id>central</id><name>central</name><url>http://${NEXUS_SERVER}/repository/maven-public/</url><mirrorOf>*</mirrorOf></mirror></mirrors></settings>" > ~/.m2/settings.xml
    - cat ~/.m2/settings.xml
    - cd backend
    - mvn package
  artifacts:
    paths:
      - backend/target/backend-*.jar

#deploy:
#  image: alpine:latest
#  stage: deploy
#  before_script:
#    - apk --update --no-cache add sshpass openssh
#  script:
#    - sshpass -p $CI_PASSWORD ssh -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o PubkeyAuthentication=no $CI_USERNAME@$CI_IP "mkdir ~/test-worked"
#  only:
#    - master
