server:
#  port: 8443
#  ssl:
#    enabled: true
#    client-auth:  want
  error:
    whitelabel:
      enabled: false
spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: validate
#    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ***REMOVED***
            client-secret: ***REMOVED***
            redirectUriTemplate: 'http://localhost:8080/{action}/oauth2/code/{registrationId}'
            iconClass: fab fa-google
          github:
            client-id: ***REMOVED***
            client-secret: ***REMOVED***
            redirectUriTemplate: 'http://localhost:8080/{action}/oauth2/code/{registrationId}'
            iconClass: fab fa-github

  profiles:
    active: default
#logging:
#  level:
#    org.hibernate: INFO
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
---
spring:
  profiles: default
---
