server:
#  port: 8443
#  ssl:
#    enabled: true
#    client-auth:  want
  error:
    whitelabel:
      enabled: false
  servlet:
    session:
      timeout: 24h
spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: none
#    show-sql: true
  liquibase:
    "change-log": "classpath:db/changelog/db.changelog-master.xml"

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ***REMOVED***
            client-secret: ***REMOVED***
            redirectUriTemplate: 'http://localhost:8080/{action}/oauth2/code/{registrationId}'
            iconClass: fab fa-google
          github:
            client-id: ***REMOVED***
            client-secret: ***REMOVED***
            redirectUriTemplate: 'http://localhost:8080/{action}/oauth2/code/{registrationId}'
            iconClass: fab fa-github
skills:
  config:
    ui:
      descriptionMaxLength: 2000
      maxTimeWindowInMinutes: 43200
      docsHost: http://skillsasaservicedocs.com
  profiles:
    active: default
#logging:
#  level:
#    org.hibernate: INFO
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
---
spring:
  profiles: default
---
